.\" Manpage for alto_client.
.\" Contact hack@jensen-zhang.site to correct errors or typos.
.TH man 1 "12 Nov 2022" "1.0" "alto_client man page"
.SH NAME
alto_client
.SH SYNOPSIS
alto_client <url> <flows> <props>
.SH DESCRIPTION
alto_client sends an ALTO format request to an ALTO server.
.SH SEE ALSO
https://github.com/openalto/alto/
